#!/bin/sh
# autopkgtest check: Build and run a simple dummy program using the AppStream lib,
# to verify that the headers and pkg-config file are installed correctly
# (c) 2014 Matthias Klumpp <mak@debian.org>
set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > asbuildtest.c
#include <appstream.h>

int main()
{
	AsComponent *cpt;
	AsMetadata *metad;
	gchar *xml_upstream;
	gchar *xml_distro;
	gchar **strv;

	cpt = as_component_new ();
	as_component_set_kind (cpt, AS_COMPONENT_KIND_DESKTOP_APP);

	as_component_set_name (cpt, "Test", "C");
	as_component_set_summary (cpt, "It does things", "C");

	strv = g_new0 (gchar*, 1 + 2);
	strv[0] = g_strdup ("fedex");
	strv[1] = NULL;
	as_component_set_pkgnames (cpt, strv);
	g_strfreev (strv);

	metad = as_metadata_new ();
	as_metadata_add_component (metad, cpt);
	xml_upstream = as_metadata_component_to_upstream_xml (metad);
	xml_distro = as_metadata_components_to_distro_xml (metad);
	g_object_unref (metad);

	g_debug ("Upstream XML: %s", xml_upstream);
	g_debug ("Distro XML: %s", xml_distro);

	g_assert_cmpstr (xml_upstream, ==, "<?xml version=\"1.0\"?>\n<component type=\"desktop\"><name>Test</name><summary>It does things</summary><pkgname>fedex</pkgname></component>\n");
	g_assert_cmpstr (xml_distro, ==, "<?xml version=\"1.0\"?>\n<components version=\"0.7\"><component type=\"desktop\"><name>Test</name><summary>It does things</summary><pkgname>fedex</pkgname></component></components>\n");

	g_free (xml_upstream);
	g_free (xml_distro);

	return 0;
}
EOF
export G_MESSAGES_DEBUG=all

gcc -o asbuildtest asbuildtest.c `pkg-config --cflags --libs appstream`
echo "build: OK"
[ -x asbuildtest ]
./asbuildtest
echo "run: OK"
